### ISSUE TITLE
Error: usbInit - undefined reference to 'usbCrc16Append' (usbdrv.c)

### ISSUE THREAD

**Issue by rdtm443** [name-is-cipher/DigiKeyboard#1]
Hey there

Thanks for this super project, really appreciate it. I constantly get this error though, during compiling:

In function `usbInit':
/DigiKeyboard/src/usbdrv.c:618: undefined reference to `usbCrc16Append'
/DigiKeyboard/src/usbdrv.c:618: undefined reference to `usbCrc16Append'
collect2: error: ld returned 1 exit status

Any idea how to fix that?

Thanks !

**Comment by cipherswami** [comment]
It's a problem with ArduinoDriod, Got a Work around for now

**Comment by cipherswami** [comment]
Work around Solution:
- Clear the Cache of ArduinoDroid
- Open ArduinoDroid and import the library without closing the app
- Now Compile
- Repeat this whole process every time you want to compile .

**Comment by rdtm443** [comment]
> Work around Solution:
> - Clear the Cache of ArduinoDroid
> - Open ArduinoDroid and import the library without closing the app
> - Now Compile
> - Repeat this whole process every time you want to compile .

Hey there. Thank you so much, appreciated !
